-- 멤버 테이블

DROP SEQUENCE MEMBER_NO_SEQ;
CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1 --증감숫자가 양수면 증가 음수면 감소 디폴트는 1
START WITH 1; -- 시작숫자의 디폴트값은 증가일때 MINVALUE 감소일때 MAXVALUE


DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	--아이디
	MEMBER_ID VARCHAR2(20) NOT NULL,
	--비밀번호
	MEMBER_PW VARCHAR2(500) NOT NULL,
	--비밀번호 체크
	MEMBER_PWCHK VARCHAR2(500) NOT NULL,
	--회원 정렬 번호
	MEMBER_NO NUMBER NOT NULL,
	--이름
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	--닉네임
	MEMBER_NICKNAME VARCHAR2(20) NOT NULL,
	--주소
	MEMBER_ADDR VARCHAR2(100) NOT NULL,
	--이메일
	MEMBER_EMAIL VARCHAR2(100) NOT NULL,
	--전화번호
	MEMBER_PHONE VARCHAR2(20) NOT NULL,
	--등급
	MEMBER_ROLE CHAR(1) NOT NULL,
	--가입여부
	MEMBER_ENABLED CHAR(1) NOT NULL,
	--가입날짜
	MEMBER_REGDATE DATE NOT NULL,
	--프로필 사진
	MEMBER_PROFILE VARCHAR2(1000), 

	CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID),
	CONSTRAINT NICKNAME_MEMBER_UNQ UNIQUE(MEMBER_NICKNAME),
	CONSTRAINT PHONE_MEMBER_UNQ UNIQUE(MEMBER_PHONE),
	CONSTRAINT EMAIL_MEMBER_UNQ UNIQUE(MEMBER_EMAIL),
	--M : 관리자 A : 아티스트 U : 일반
	CONSTRAINT MEMBER_ROLE_MEMBER_CHK CHECK(MEMBER_ROLE IN('M', 'A', 'U')),
	--Y - 일반회원, N - 탈퇴한 회원, R - 신고된 회원
	CONSTRAINT ENABLED_MEMBER_CHK CHECK(MEMBER_ENABLED IN('Y','N','A'))
);

INSERT INTO MEMBER
VALUES( 'admin', 'admin1234', 'admin1234', MEMBER_NO_SEQ.NEXTVAL , '관리자', '관리자', '서울시 강남구', 'email', '010-1234-1234', 'M', 'Y', SYSDATE, null);

SELECT *
FROM MEMBER;